name = "DynamicGridsInteract"
uuid = "3ccff026-9a20-11e9-1704-43e1c6ed0af5"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.5.5"

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
DynamicGrids = "a5dba43e-3abc-5203-bfc5-584ca68d3f5b"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
InteractBase = "d3863d7c-f0c8-5437-a7b4-3ae773c01009"
InteractModels = "546b680c-e627-4c75-86f8-7ef2c81e5d51"
Mux = "a975b10e-0019-58db-a62f-e48ff68538c9"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"

[compat]
Blink = "0.12"
DynamicGrids = "^0.18.4"
ImageShow = "0.2.3, 0.3"
Interact = "0.10"
InteractBase = "0.10"
InteractModels = "0.4"
Mux = "0.7"
WebIO = "0.8"
WebSockets = "1"
julia = "1"

[extras]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Colors", "ColorSchemes", "ImageMagick", "Test"]
